name = "umwi"
description = "Unicode Monospace Width Information"
version = "0.2.0"

authors = ["Alejandro R. Mosteo"]
maintainers = ["Alejandro R. Mosteo <alejandro@mosteo.com>"]
maintainers-logins = ["mosteo"]
licenses = "LGPL-3.0-or-later"
website = ""
tags = ["unicode", "emoji", "emoticon", "monospace", "east", "asian", "width", "grapheme", "cluster", "combining"]

[origin]
commit = "7b17f2c9823dae0e0f954c1aa970c5af43f3a263"
url = "git+https://github.com/mosteo/umwi.git"

