name = "umwi"
description = "Unicode Monospace Width Information"
version = "1.0-1"

authors = ["Alejandro R. Mosteo"]
maintainers = ["Alejandro R. Mosteo <alejandro@mosteo.com>"]
maintainers-logins = ["mosteo"]
licenses = "LGPL-3.0-or-later"
website = ""
tags = ["unicode", "emoji", "emoticon", "monospace", "east", "asian", "width", "grapheme", "cluster", "combining"]

[build-switches]
"*".Ada_Version = "Ada2022"

[origin]
commit = "d0378b0fdb5487d8c8657910a2d6e2160fef708c"
url = "git+https://github.com/mosteo/umwi.git"

